// get all notes
export const NOTES_LOAD_REQUEST = "NOTES_LOAD_REQUEST"
export const NOTES_LOAD_SUCCESS = "NOTES_LOAD_SUCCESS"
export const NOTES_LOAD_FAILURE = "NOTES_LOAD_FAILURE"

// create new note
export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST"
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS"
export const CREATE_NOTE_FAILURE = "CREATE_NOTE_FAILURE"  